# Generated by Django 3.2.18 on 2023-04-23 23:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('budgets', '0001_initial'),
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitMeasure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acronym', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'unitmeasure',
            },
        ),
        migrations.CreateModel(
            name='AccountingEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('type_accounting_entry', models.IntegerField()),
                ('observation', models.CharField(blank=True, max_length=100, null=True)),
                ('deleted', models.BooleanField()),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='accounting_entries', to='budgets.budget')),
                ('classification', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='accounting_entries', to='companies.classification')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='accounting_entries', to='companies.company')),
                ('cost_center', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='accounting_entries', to='budgets.costcenter')),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='accounting_entries', to='companies.goal')),
            ],
            options={
                'db_table': 'accountingentry',
            },
        ),
    ]
